# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Brian/Dropbox/Magnate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Brian/Dropbox/Magnate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Brian/Dropbox/Magnate/CMakeFiles /Users/Brian/Dropbox/Magnate/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Brian/Dropbox/Magnate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Magnate

# Build rule for target.
Magnate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Magnate
.PHONY : Magnate

# fast build rule for target.
Magnate/fast:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/build
.PHONY : Magnate/fast

src/Atlas.o: src/Atlas.cpp.o
.PHONY : src/Atlas.o

# target to build an object file
src/Atlas.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Atlas.cpp.o
.PHONY : src/Atlas.cpp.o

src/Atlas.i: src/Atlas.cpp.i
.PHONY : src/Atlas.i

# target to preprocess a source file
src/Atlas.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Atlas.cpp.i
.PHONY : src/Atlas.cpp.i

src/Atlas.s: src/Atlas.cpp.s
.PHONY : src/Atlas.s

# target to generate assembly for a file
src/Atlas.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Atlas.cpp.s
.PHONY : src/Atlas.cpp.s

src/Building.o: src/Building.cpp.o
.PHONY : src/Building.o

# target to build an object file
src/Building.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Building.cpp.o
.PHONY : src/Building.cpp.o

src/Building.i: src/Building.cpp.i
.PHONY : src/Building.i

# target to preprocess a source file
src/Building.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Building.cpp.i
.PHONY : src/Building.cpp.i

src/Building.s: src/Building.cpp.s
.PHONY : src/Building.s

# target to generate assembly for a file
src/Building.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Building.cpp.s
.PHONY : src/Building.cpp.s

src/Button.o: src/Button.cpp.o
.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i
.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s
.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Component.o: src/Component.cpp.o
.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i
.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s
.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/Coord.o: src/Coord.cpp.o
.PHONY : src/Coord.o

# target to build an object file
src/Coord.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Coord.cpp.o
.PHONY : src/Coord.cpp.o

src/Coord.i: src/Coord.cpp.i
.PHONY : src/Coord.i

# target to preprocess a source file
src/Coord.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Coord.cpp.i
.PHONY : src/Coord.cpp.i

src/Coord.s: src/Coord.cpp.s
.PHONY : src/Coord.s

# target to generate assembly for a file
src/Coord.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Coord.cpp.s
.PHONY : src/Coord.cpp.s

src/Draggable.o: src/Draggable.cpp.o
.PHONY : src/Draggable.o

# target to build an object file
src/Draggable.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Draggable.cpp.o
.PHONY : src/Draggable.cpp.o

src/Draggable.i: src/Draggable.cpp.i
.PHONY : src/Draggable.i

# target to preprocess a source file
src/Draggable.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Draggable.cpp.i
.PHONY : src/Draggable.cpp.i

src/Draggable.s: src/Draggable.cpp.s
.PHONY : src/Draggable.s

# target to generate assembly for a file
src/Draggable.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Draggable.cpp.s
.PHONY : src/Draggable.cpp.s

src/Erosion.o: src/Erosion.cpp.o
.PHONY : src/Erosion.o

# target to build an object file
src/Erosion.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Erosion.cpp.o
.PHONY : src/Erosion.cpp.o

src/Erosion.i: src/Erosion.cpp.i
.PHONY : src/Erosion.i

# target to preprocess a source file
src/Erosion.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Erosion.cpp.i
.PHONY : src/Erosion.cpp.i

src/Erosion.s: src/Erosion.cpp.s
.PHONY : src/Erosion.s

# target to generate assembly for a file
src/Erosion.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Erosion.cpp.s
.PHONY : src/Erosion.cpp.s

src/Field.o: src/Field.cpp.o
.PHONY : src/Field.o

# target to build an object file
src/Field.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Field.cpp.o
.PHONY : src/Field.cpp.o

src/Field.i: src/Field.cpp.i
.PHONY : src/Field.i

# target to preprocess a source file
src/Field.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Field.cpp.i
.PHONY : src/Field.cpp.i

src/Field.s: src/Field.cpp.s
.PHONY : src/Field.s

# target to generate assembly for a file
src/Field.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Field.cpp.s
.PHONY : src/Field.cpp.s

src/FileIO.o: src/FileIO.cpp.o
.PHONY : src/FileIO.o

# target to build an object file
src/FileIO.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/FileIO.cpp.o
.PHONY : src/FileIO.cpp.o

src/FileIO.i: src/FileIO.cpp.i
.PHONY : src/FileIO.i

# target to preprocess a source file
src/FileIO.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/FileIO.cpp.i
.PHONY : src/FileIO.cpp.i

src/FileIO.s: src/FileIO.cpp.s
.PHONY : src/FileIO.s

# target to generate assembly for a file
src/FileIO.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/FileIO.cpp.s
.PHONY : src/FileIO.cpp.s

src/GUI.o: src/GUI.cpp.o
.PHONY : src/GUI.o

# target to build an object file
src/GUI.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GUI.cpp.o
.PHONY : src/GUI.cpp.o

src/GUI.i: src/GUI.cpp.i
.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s
.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GenTypes.o: src/GenTypes.cpp.o
.PHONY : src/GenTypes.o

# target to build an object file
src/GenTypes.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GenTypes.cpp.o
.PHONY : src/GenTypes.cpp.o

src/GenTypes.i: src/GenTypes.cpp.i
.PHONY : src/GenTypes.i

# target to preprocess a source file
src/GenTypes.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GenTypes.cpp.i
.PHONY : src/GenTypes.cpp.i

src/GenTypes.s: src/GenTypes.cpp.s
.PHONY : src/GenTypes.s

# target to generate assembly for a file
src/GenTypes.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GenTypes.cpp.s
.PHONY : src/GenTypes.cpp.s

src/GlmHeaders.o: src/GlmHeaders.cpp.o
.PHONY : src/GlmHeaders.o

# target to build an object file
src/GlmHeaders.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GlmHeaders.cpp.o
.PHONY : src/GlmHeaders.cpp.o

src/GlmHeaders.i: src/GlmHeaders.cpp.i
.PHONY : src/GlmHeaders.i

# target to preprocess a source file
src/GlmHeaders.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GlmHeaders.cpp.i
.PHONY : src/GlmHeaders.cpp.i

src/GlmHeaders.s: src/GlmHeaders.cpp.s
.PHONY : src/GlmHeaders.s

# target to generate assembly for a file
src/GlmHeaders.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GlmHeaders.cpp.s
.PHONY : src/GlmHeaders.cpp.s

src/GlobalConfig.o: src/GlobalConfig.cpp.o
.PHONY : src/GlobalConfig.o

# target to build an object file
src/GlobalConfig.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GlobalConfig.cpp.o
.PHONY : src/GlobalConfig.cpp.o

src/GlobalConfig.i: src/GlobalConfig.cpp.i
.PHONY : src/GlobalConfig.i

# target to preprocess a source file
src/GlobalConfig.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GlobalConfig.cpp.i
.PHONY : src/GlobalConfig.cpp.i

src/GlobalConfig.s: src/GlobalConfig.cpp.s
.PHONY : src/GlobalConfig.s

# target to generate assembly for a file
src/GlobalConfig.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/GlobalConfig.cpp.s
.PHONY : src/GlobalConfig.cpp.s

src/Heightmap.o: src/Heightmap.cpp.o
.PHONY : src/Heightmap.o

# target to build an object file
src/Heightmap.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Heightmap.cpp.o
.PHONY : src/Heightmap.cpp.o

src/Heightmap.i: src/Heightmap.cpp.i
.PHONY : src/Heightmap.i

# target to preprocess a source file
src/Heightmap.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Heightmap.cpp.i
.PHONY : src/Heightmap.cpp.i

src/Heightmap.s: src/Heightmap.cpp.s
.PHONY : src/Heightmap.s

# target to generate assembly for a file
src/Heightmap.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Heightmap.cpp.s
.PHONY : src/Heightmap.cpp.s

src/ImmediateDraw.o: src/ImmediateDraw.cpp.o
.PHONY : src/ImmediateDraw.o

# target to build an object file
src/ImmediateDraw.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/ImmediateDraw.cpp.o
.PHONY : src/ImmediateDraw.cpp.o

src/ImmediateDraw.i: src/ImmediateDraw.cpp.i
.PHONY : src/ImmediateDraw.i

# target to preprocess a source file
src/ImmediateDraw.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/ImmediateDraw.cpp.i
.PHONY : src/ImmediateDraw.cpp.i

src/ImmediateDraw.s: src/ImmediateDraw.cpp.s
.PHONY : src/ImmediateDraw.s

# target to generate assembly for a file
src/ImmediateDraw.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/ImmediateDraw.cpp.s
.PHONY : src/ImmediateDraw.cpp.s

src/Input.o: src/Input.cpp.o
.PHONY : src/Input.o

# target to build an object file
src/Input.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Input.cpp.o
.PHONY : src/Input.cpp.o

src/Input.i: src/Input.cpp.i
.PHONY : src/Input.i

# target to preprocess a source file
src/Input.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Input.cpp.i
.PHONY : src/Input.cpp.i

src/Input.s: src/Input.cpp.s
.PHONY : src/Input.s

# target to generate assembly for a file
src/Input.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Input.cpp.s
.PHONY : src/Input.cpp.s

src/Label.o: src/Label.cpp.o
.PHONY : src/Label.o

# target to build an object file
src/Label.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Label.cpp.o
.PHONY : src/Label.cpp.o

src/Label.i: src/Label.cpp.i
.PHONY : src/Label.i

# target to preprocess a source file
src/Label.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Label.cpp.i
.PHONY : src/Label.cpp.i

src/Label.s: src/Label.cpp.s
.PHONY : src/Label.s

# target to generate assembly for a file
src/Label.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Label.cpp.s
.PHONY : src/Label.cpp.s

src/LinAlg.o: src/LinAlg.cpp.o
.PHONY : src/LinAlg.o

# target to build an object file
src/LinAlg.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/LinAlg.cpp.o
.PHONY : src/LinAlg.cpp.o

src/LinAlg.i: src/LinAlg.cpp.i
.PHONY : src/LinAlg.i

# target to preprocess a source file
src/LinAlg.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/LinAlg.cpp.i
.PHONY : src/LinAlg.cpp.i

src/LinAlg.s: src/LinAlg.cpp.s
.PHONY : src/LinAlg.s

# target to generate assembly for a file
src/LinAlg.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/LinAlg.cpp.s
.PHONY : src/LinAlg.cpp.s

src/Menus.o: src/Menus.cpp.o
.PHONY : src/Menus.o

# target to build an object file
src/Menus.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Menus.cpp.o
.PHONY : src/Menus.cpp.o

src/Menus.i: src/Menus.cpp.i
.PHONY : src/Menus.i

# target to preprocess a source file
src/Menus.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Menus.cpp.i
.PHONY : src/Menus.cpp.i

src/Menus.s: src/Menus.cpp.s
.PHONY : src/Menus.s

# target to generate assembly for a file
src/Menus.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Menus.cpp.s
.PHONY : src/Menus.cpp.s

src/Minimap.o: src/Minimap.cpp.o
.PHONY : src/Minimap.o

# target to build an object file
src/Minimap.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Minimap.cpp.o
.PHONY : src/Minimap.cpp.o

src/Minimap.i: src/Minimap.cpp.i
.PHONY : src/Minimap.i

# target to preprocess a source file
src/Minimap.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Minimap.cpp.i
.PHONY : src/Minimap.cpp.i

src/Minimap.s: src/Minimap.cpp.s
.PHONY : src/Minimap.s

# target to generate assembly for a file
src/Minimap.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Minimap.cpp.s
.PHONY : src/Minimap.cpp.s

src/Models.o: src/Models.cpp.o
.PHONY : src/Models.o

# target to build an object file
src/Models.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Models.cpp.o
.PHONY : src/Models.cpp.o

src/Models.i: src/Models.cpp.i
.PHONY : src/Models.i

# target to preprocess a source file
src/Models.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Models.cpp.i
.PHONY : src/Models.cpp.i

src/Models.s: src/Models.cpp.s
.PHONY : src/Models.s

# target to generate assembly for a file
src/Models.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Models.cpp.s
.PHONY : src/Models.cpp.s

src/MultiSelect.o: src/MultiSelect.cpp.o
.PHONY : src/MultiSelect.o

# target to build an object file
src/MultiSelect.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/MultiSelect.cpp.o
.PHONY : src/MultiSelect.cpp.o

src/MultiSelect.i: src/MultiSelect.cpp.i
.PHONY : src/MultiSelect.i

# target to preprocess a source file
src/MultiSelect.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/MultiSelect.cpp.i
.PHONY : src/MultiSelect.cpp.i

src/MultiSelect.s: src/MultiSelect.cpp.s
.PHONY : src/MultiSelect.s

# target to generate assembly for a file
src/MultiSelect.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/MultiSelect.cpp.s
.PHONY : src/MultiSelect.cpp.s

src/RandomUtils.o: src/RandomUtils.cpp.o
.PHONY : src/RandomUtils.o

# target to build an object file
src/RandomUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/RandomUtils.cpp.o
.PHONY : src/RandomUtils.cpp.o

src/RandomUtils.i: src/RandomUtils.cpp.i
.PHONY : src/RandomUtils.i

# target to preprocess a source file
src/RandomUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/RandomUtils.cpp.i
.PHONY : src/RandomUtils.cpp.i

src/RandomUtils.s: src/RandomUtils.cpp.s
.PHONY : src/RandomUtils.s

# target to generate assembly for a file
src/RandomUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/RandomUtils.cpp.s
.PHONY : src/RandomUtils.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/SaveManager.o: src/SaveManager.cpp.o
.PHONY : src/SaveManager.o

# target to build an object file
src/SaveManager.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/SaveManager.cpp.o
.PHONY : src/SaveManager.cpp.o

src/SaveManager.i: src/SaveManager.cpp.i
.PHONY : src/SaveManager.i

# target to preprocess a source file
src/SaveManager.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/SaveManager.cpp.i
.PHONY : src/SaveManager.cpp.i

src/SaveManager.s: src/SaveManager.cpp.s
.PHONY : src/SaveManager.s

# target to generate assembly for a file
src/SaveManager.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/SaveManager.cpp.s
.PHONY : src/SaveManager.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/ScrollBlock.o: src/ScrollBlock.cpp.o
.PHONY : src/ScrollBlock.o

# target to build an object file
src/ScrollBlock.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/ScrollBlock.cpp.o
.PHONY : src/ScrollBlock.cpp.o

src/ScrollBlock.i: src/ScrollBlock.cpp.i
.PHONY : src/ScrollBlock.i

# target to preprocess a source file
src/ScrollBlock.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/ScrollBlock.cpp.i
.PHONY : src/ScrollBlock.cpp.i

src/ScrollBlock.s: src/ScrollBlock.cpp.s
.PHONY : src/ScrollBlock.s

# target to generate assembly for a file
src/ScrollBlock.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/ScrollBlock.cpp.s
.PHONY : src/ScrollBlock.cpp.s

src/Shaders.o: src/Shaders.cpp.o
.PHONY : src/Shaders.o

# target to build an object file
src/Shaders.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Shaders.cpp.o
.PHONY : src/Shaders.cpp.o

src/Shaders.i: src/Shaders.cpp.i
.PHONY : src/Shaders.i

# target to preprocess a source file
src/Shaders.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Shaders.cpp.i
.PHONY : src/Shaders.cpp.i

src/Shaders.s: src/Shaders.cpp.s
.PHONY : src/Shaders.s

# target to generate assembly for a file
src/Shaders.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Shaders.cpp.s
.PHONY : src/Shaders.cpp.s

src/Terrain.o: src/Terrain.cpp.o
.PHONY : src/Terrain.o

# target to build an object file
src/Terrain.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Terrain.cpp.o
.PHONY : src/Terrain.cpp.o

src/Terrain.i: src/Terrain.cpp.i
.PHONY : src/Terrain.i

# target to preprocess a source file
src/Terrain.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Terrain.cpp.i
.PHONY : src/Terrain.cpp.i

src/Terrain.s: src/Terrain.cpp.s
.PHONY : src/Terrain.s

# target to generate assembly for a file
src/Terrain.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Terrain.cpp.s
.PHONY : src/Terrain.cpp.s

src/TerrainGen.o: src/TerrainGen.cpp.o
.PHONY : src/TerrainGen.o

# target to build an object file
src/TerrainGen.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TerrainGen.cpp.o
.PHONY : src/TerrainGen.cpp.o

src/TerrainGen.i: src/TerrainGen.cpp.i
.PHONY : src/TerrainGen.i

# target to preprocess a source file
src/TerrainGen.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TerrainGen.cpp.i
.PHONY : src/TerrainGen.cpp.i

src/TerrainGen.s: src/TerrainGen.cpp.s
.PHONY : src/TerrainGen.s

# target to generate assembly for a file
src/TerrainGen.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TerrainGen.cpp.s
.PHONY : src/TerrainGen.cpp.s

src/TexGen.o: src/TexGen.cpp.o
.PHONY : src/TexGen.o

# target to build an object file
src/TexGen.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TexGen.cpp.o
.PHONY : src/TexGen.cpp.o

src/TexGen.i: src/TexGen.cpp.i
.PHONY : src/TexGen.i

# target to preprocess a source file
src/TexGen.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TexGen.cpp.i
.PHONY : src/TexGen.cpp.i

src/TexGen.s: src/TexGen.cpp.s
.PHONY : src/TexGen.s

# target to generate assembly for a file
src/TexGen.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TexGen.cpp.s
.PHONY : src/TexGen.cpp.s

src/TexManager.o: src/TexManager.cpp.o
.PHONY : src/TexManager.o

# target to build an object file
src/TexManager.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TexManager.cpp.o
.PHONY : src/TexManager.cpp.o

src/TexManager.i: src/TexManager.cpp.i
.PHONY : src/TexManager.i

# target to preprocess a source file
src/TexManager.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TexManager.cpp.i
.PHONY : src/TexManager.cpp.i

src/TexManager.s: src/TexManager.cpp.s
.PHONY : src/TexManager.s

# target to generate assembly for a file
src/TexManager.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/TexManager.cpp.s
.PHONY : src/TexManager.cpp.s

src/Topo.o: src/Topo.cpp.o
.PHONY : src/Topo.o

# target to build an object file
src/Topo.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Topo.cpp.o
.PHONY : src/Topo.cpp.o

src/Topo.i: src/Topo.cpp.i
.PHONY : src/Topo.i

# target to preprocess a source file
src/Topo.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Topo.cpp.i
.PHONY : src/Topo.cpp.i

src/Topo.s: src/Topo.cpp.s
.PHONY : src/Topo.s

# target to generate assembly for a file
src/Topo.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Topo.cpp.s
.PHONY : src/Topo.cpp.s

src/UIRenderer.o: src/UIRenderer.cpp.o
.PHONY : src/UIRenderer.o

# target to build an object file
src/UIRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/UIRenderer.cpp.o
.PHONY : src/UIRenderer.cpp.o

src/UIRenderer.i: src/UIRenderer.cpp.i
.PHONY : src/UIRenderer.i

# target to preprocess a source file
src/UIRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/UIRenderer.cpp.i
.PHONY : src/UIRenderer.cpp.i

src/UIRenderer.s: src/UIRenderer.cpp.s
.PHONY : src/UIRenderer.s

# target to generate assembly for a file
src/UIRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/UIRenderer.cpp.s
.PHONY : src/UIRenderer.cpp.s

src/VBO.o: src/VBO.cpp.o
.PHONY : src/VBO.o

# target to build an object file
src/VBO.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/VBO.cpp.o
.PHONY : src/VBO.cpp.o

src/VBO.i: src/VBO.cpp.i
.PHONY : src/VBO.i

# target to preprocess a source file
src/VBO.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/VBO.cpp.i
.PHONY : src/VBO.cpp.i

src/VBO.s: src/VBO.cpp.s
.PHONY : src/VBO.s

# target to generate assembly for a file
src/VBO.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/VBO.cpp.s
.PHONY : src/VBO.cpp.s

src/Watershed.o: src/Watershed.cpp.o
.PHONY : src/Watershed.o

# target to build an object file
src/Watershed.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Watershed.cpp.o
.PHONY : src/Watershed.cpp.o

src/Watershed.i: src/Watershed.cpp.i
.PHONY : src/Watershed.i

# target to preprocess a source file
src/Watershed.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Watershed.cpp.i
.PHONY : src/Watershed.cpp.i

src/Watershed.s: src/Watershed.cpp.s
.PHONY : src/Watershed.s

# target to generate assembly for a file
src/Watershed.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Watershed.cpp.s
.PHONY : src/Watershed.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/World.o: src/World.cpp.o
.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/WorldRenderer.o: src/WorldRenderer.cpp.o
.PHONY : src/WorldRenderer.o

# target to build an object file
src/WorldRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/WorldRenderer.cpp.o
.PHONY : src/WorldRenderer.cpp.o

src/WorldRenderer.i: src/WorldRenderer.cpp.i
.PHONY : src/WorldRenderer.i

# target to preprocess a source file
src/WorldRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/WorldRenderer.cpp.i
.PHONY : src/WorldRenderer.cpp.i

src/WorldRenderer.s: src/WorldRenderer.cpp.s
.PHONY : src/WorldRenderer.s

# target to generate assembly for a file
src/WorldRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/WorldRenderer.cpp.s
.PHONY : src/WorldRenderer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Magnate.dir/build.make CMakeFiles/Magnate.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Magnate"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Atlas.o"
	@echo "... src/Atlas.i"
	@echo "... src/Atlas.s"
	@echo "... src/Building.o"
	@echo "... src/Building.i"
	@echo "... src/Building.s"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/Coord.o"
	@echo "... src/Coord.i"
	@echo "... src/Coord.s"
	@echo "... src/Draggable.o"
	@echo "... src/Draggable.i"
	@echo "... src/Draggable.s"
	@echo "... src/Erosion.o"
	@echo "... src/Erosion.i"
	@echo "... src/Erosion.s"
	@echo "... src/Field.o"
	@echo "... src/Field.i"
	@echo "... src/Field.s"
	@echo "... src/FileIO.o"
	@echo "... src/FileIO.i"
	@echo "... src/FileIO.s"
	@echo "... src/GUI.o"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GenTypes.o"
	@echo "... src/GenTypes.i"
	@echo "... src/GenTypes.s"
	@echo "... src/GlmHeaders.o"
	@echo "... src/GlmHeaders.i"
	@echo "... src/GlmHeaders.s"
	@echo "... src/GlobalConfig.o"
	@echo "... src/GlobalConfig.i"
	@echo "... src/GlobalConfig.s"
	@echo "... src/Heightmap.o"
	@echo "... src/Heightmap.i"
	@echo "... src/Heightmap.s"
	@echo "... src/ImmediateDraw.o"
	@echo "... src/ImmediateDraw.i"
	@echo "... src/ImmediateDraw.s"
	@echo "... src/Input.o"
	@echo "... src/Input.i"
	@echo "... src/Input.s"
	@echo "... src/Label.o"
	@echo "... src/Label.i"
	@echo "... src/Label.s"
	@echo "... src/LinAlg.o"
	@echo "... src/LinAlg.i"
	@echo "... src/LinAlg.s"
	@echo "... src/Menus.o"
	@echo "... src/Menus.i"
	@echo "... src/Menus.s"
	@echo "... src/Minimap.o"
	@echo "... src/Minimap.i"
	@echo "... src/Minimap.s"
	@echo "... src/Models.o"
	@echo "... src/Models.i"
	@echo "... src/Models.s"
	@echo "... src/MultiSelect.o"
	@echo "... src/MultiSelect.i"
	@echo "... src/MultiSelect.s"
	@echo "... src/RandomUtils.o"
	@echo "... src/RandomUtils.i"
	@echo "... src/RandomUtils.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/SaveManager.o"
	@echo "... src/SaveManager.i"
	@echo "... src/SaveManager.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/ScrollBlock.o"
	@echo "... src/ScrollBlock.i"
	@echo "... src/ScrollBlock.s"
	@echo "... src/Shaders.o"
	@echo "... src/Shaders.i"
	@echo "... src/Shaders.s"
	@echo "... src/Terrain.o"
	@echo "... src/Terrain.i"
	@echo "... src/Terrain.s"
	@echo "... src/TerrainGen.o"
	@echo "... src/TerrainGen.i"
	@echo "... src/TerrainGen.s"
	@echo "... src/TexGen.o"
	@echo "... src/TexGen.i"
	@echo "... src/TexGen.s"
	@echo "... src/TexManager.o"
	@echo "... src/TexManager.i"
	@echo "... src/TexManager.s"
	@echo "... src/Topo.o"
	@echo "... src/Topo.i"
	@echo "... src/Topo.s"
	@echo "... src/UIRenderer.o"
	@echo "... src/UIRenderer.i"
	@echo "... src/UIRenderer.s"
	@echo "... src/VBO.o"
	@echo "... src/VBO.i"
	@echo "... src/VBO.s"
	@echo "... src/Watershed.o"
	@echo "... src/Watershed.i"
	@echo "... src/Watershed.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/WorldRenderer.o"
	@echo "... src/WorldRenderer.i"
	@echo "... src/WorldRenderer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

