# Generated by CMake, DO NOT EDIT
/Users/Brian/Dropbox/Magnate/macBuild/CMakeFiles/cmake.check_cache: \
/Users/Brian/Dropbox/Magnate/CMakeLists.txt\
/Users/Brian/Dropbox/Magnate/macBuild/CMakeFiles/3.0.2/CMakeCCompiler.cmake\
/Users/Brian/Dropbox/Magnate/macBuild/CMakeFiles/3.0.2/CMakeCXXCompiler.cmake\
/Users/Brian/Dropbox/Magnate/macBuild/CMakeFiles/3.0.2/CMakeSystem.cmake\
/usr/local/share/cmake-3.0/Modules/CMakeCInformation.cmake\
/usr/local/share/cmake-3.0/Modules/CMakeCXXInformation.cmake\
/usr/local/share/cmake-3.0/Modules/CMakeCommonLanguageInclude.cmake\
/usr/local/share/cmake-3.0/Modules/CMakeGenericSystem.cmake\
/usr/local/share/cmake-3.0/Modules/CMakeSystemSpecificInformation.cmake\
/usr/local/share/cmake-3.0/Modules/Compiler/AppleClang-C.cmake\
/usr/local/share/cmake-3.0/Modules/Compiler/AppleClang-CXX.cmake\
/usr/local/share/cmake-3.0/Modules/Compiler/Clang-C.cmake\
/usr/local/share/cmake-3.0/Modules/Compiler/Clang-CXX.cmake\
/usr/local/share/cmake-3.0/Modules/Compiler/Clang.cmake\
/usr/local/share/cmake-3.0/Modules/Compiler/GNU.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/Darwin-AppleClang-C.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/Darwin-AppleClang-CXX.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/Darwin-Clang-C.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/Darwin-Clang-CXX.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/Darwin-Clang.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/Darwin.cmake\
/usr/local/share/cmake-3.0/Modules/Platform/UnixPaths.cmake
	/usr/local/bin/cmake -H/Users/Brian/Dropbox/Magnate -B/Users/Brian/Dropbox/Magnate/macBuild
